export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID!;
export const IMAGES_BUCKET_ID = process.env.NEXT_PUBLIC_IMAGES_BUCKET_ID!;
